deployment:
  image:
    registry: ""
    name: sefaria-llm
    imagePullPolicy: IfNotPresent
  # Noah, please provide sane values here
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      cpu: 200m
      memory: 1Gi
  secretRef: ""
redis:
  url: "redis://127.0.0.1"
  port: 6397
  DBNumber: 0
  backendDBNUmber: 1
  sentinelURL: ""
  transportOptions: {}
