deployment:
  replicaCount: 1
  image:
    # tag: ""
    registry: ""
    name: sefaria-llm
    imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 1000m
      memory: 500Mi
    limits:
      cpu: 2000m
      memory: 5Gi
  anthropicSecretRef: anthropic-api-key
  openaiSecretRef: openai-api-key
redis:
  url: "redis://127.0.0.1"
  port: "6397"
  brokerDBNumber: "0"
  resultBackendDBNumber: "1"
  sentinelURL: ""
  transportOptions: {}
  redisPassword:
    ref: redis-password
  sentinelPassword:
    ref: sentinel-password
