apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "llm.labels" . | nindent 4 }}
data:
  REDIS_URL: {{ .Values.redis.url }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  REDIS_BROKER_DB_NUM: {{ .Values.redis.brokerDBNumber | quote }}
  REDIS_RESULT_BACKEND_DB_NUM: {{ .Values.redis.resultBackendDBNumber | quote }}
  SENTINEL_HEADLESS_URL: {{ .Values.redis.sentinelURL }}
  SENTINEL_TRANSPORT_OPTS: {{ .Values.redis.transportOptions | toJson | quote }}
  QUEUE_NAME: llm-{{ .Release.Name }}
