apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
  namespace: {{ .Release.Namespace }}
data:
  REDIS_URL: {{ .Values.redis.url }}
  REDIS_PORT: {{ .Values.redis.port }}
  REDIS_BROKER_DB_NUM: {{ .Values.redis.DBNumber }}
  REDIS_RESULT_BACKEND_DB_NUM: {{ .Values.redis.backendDBNumber }}
  SENTINEL_HEADLESS_URL: {{ .Values.redis.sentinelURL }}
  SENTINEL_TRANSPORT_OPTS: {{ .Values.redis.transportOptions | toJson | quote }}
  QUEUE_NAME: llm-{{ .Release.Name }}
