apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    # Helper labels
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.deployment.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      # Helper labels
  template:
    metadata:
      labels:
        # Helper labels
    spec:
      containers:
      - name: llm
        image: "{{ .Values.deployment.image.registry }}/{{ .Values.deploment.image.name }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}
        - secretRef:
            name: {{ .Values.deployment.secretRef }}
        resources: {{ .Values.deployment.resources | toYaml | nindent 10 }}`
