apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.deployment.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:  {{ include "llm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "llm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: llm
        image: "{{ .Values.deployment.image.registry }}/{{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}
        - secretRef:
            name: {{ .Values.deployment.anthropicSecretRef }}
        - secretRef:
            name: {{ .Values.deployment.openaiSecretRef }}
        - secretRef:
            name: {{ .Values.deployment.redisSecretRef }}
        resources: {{ .Values.deployment.resources | toYaml | nindent 10 }}
