vars:
  # base_model: "gpt-3.5-turbo"
  base_model: "davinci-002"
  input_collection: "ner_en_gpt_gold"
  output_model_suffix: "en-ner"
  # output_model_suffix: "en-entity-class"
env:
  openai_api_key: OPENAI_API_KEY
workflows:
  all:
    - create_citation_ner_training
    - create_citation_classification_training
    - upload_files
    - create_fine_tune

commands:
  - name: create_citation_ner_training
    script:
      - 'python project_scripts/create_citation_input_for_fine_tuning.py ${vars.input_collection} ner output/gpt_citation_training.jsonl output/gpt_citation_validation.jsonl -m localhost -p 27017'
    outputs:
      - 'output/gpt_citation_training.jsonl'
      - 'output/gpt_citation_validation.jsonl'

  - name: create_citation_classification_training
    script:
      - 'python project_scripts/create_citation_input_for_fine_tuning.py ${vars.input_collection} entity_classification output/gpt_citation_training.jsonl output/gpt_citation_validation.jsonl -m localhost -p 27017'
    outputs:
      - 'output/gpt_citation_training.jsonl'
      - 'output/gpt_citation_validation.jsonl'

  - name: delete_all_files
    script:
      - "python ../../util/fine_tune/delete_all_files.py"

  - name: delete_all_fine_tunes
    script:
      - "python ../../util/fine_tune/delete_all_fine_tunes.py"

  - name: delete_last_fine_tune_job
    script:
      - "python ../../util/fine_tune/delete_last_fine_tune_job.py"

  - name: upload_files
    deps:
      - 'output/gpt_citation_training.jsonl'
      - 'output/gpt_citation_validation.jsonl'
    outputs:
      - 'output/fine_tune_file_ids.json'
    script:
      - 'python ../../util/fine_tune/upload_fine_tune_files.py output/gpt_citation_training.jsonl output/gpt_citation_validation.jsonl'


  - name: create_fine_tune
    deps:
      - 'output/fine_tune_file_ids.json'
    script:
      - 'python ../../util/fine_tune/create_fine_tune.py ${vars.base_model} ${vars.output_model_suffix}'

  - name: fine_tune_status
    script:
      - 'python ../../util/fine_tune/fine_tune_status.py'

  - name: fine_tune_stats
    outputs:
      - 'output/fine_tune_stats.csv'
    script:
      - '../../util/fine_tune/fine_tune_stats.sh ${env.openai_api_key} "file-VRP52zJ1ETBX6crq0vfidXqb" output/fine_tune_stats.csv'
